# Generated by Django 2.0.13 on 2019-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasCRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiasmodelo',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
    ]
