# Generated by Django 2.0.13 on 2019-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasCRUD', '0002_auto_20190502_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiasmodelo',
            name='subtitulo',
        ),
        migrations.AlterField(
            model_name='noticiasmodelo',
            name='tipoChoice',
            field=models.CharField(choices=[('Noticia', 'Noticias'), ('Evento', 'Eventos')], default='Noticia', max_length=10),
        ),
    ]
