# Generated by Django 2.0.13 on 2019-05-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoticiasCRUD', '0003_auto_20190503_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticiasmodelo',
            name='tipoChoice',
        ),
        migrations.AddField(
            model_name='noticiasmodelo',
            name='tipo',
            field=models.CharField(choices=[('N', 'Noticias'), ('E', 'Eventos')], default='N', max_length=1),
        ),
    ]
