# Generated by Django 2.0.13 on 2019-05-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=10)),
                ('resumen', models.CharField(max_length=200)),
                ('detalle', models.CharField(max_length=500)),
                ('tipoChoice', models.CharField(choices=[('Noticia', 'Noticias'), ('Evento', 'Eventos')], default='Noticia', max_length=10)),
            ],
        ),
    ]
