# Generated by Django 2.0.13 on 2019-05-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VistaWEB', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticiaModelo',
        ),
    ]
